name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy_production:
    uses: ./.github/workflows/portfolio-production-deploy.yml
    with:
      commit_sha: ${{ github.sha }}
      base_sha: ${{ github.event.before }}
    secrets: inherit
